# Generated by Django 3.2.6 on 2022-01-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cenario',
            options={'ordering': ['nome', 'data_criacao'], 'verbose_name': 'Cenário', 'verbose_name_plural': 'Cenários'},
        ),
        migrations.AddField(
            model_name='cenario',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='cenario/', verbose_name='Imagem'),
        ),
    ]
