# Generated by Django 3.2.6 on 2022-01-02 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_hp', models.PositiveSmallIntegerField(verbose_name='HP Máximo')),
                ('max_mp', models.PositiveSmallIntegerField(verbose_name='MP Máximo')),
                ('forca', models.SmallIntegerField(verbose_name='Força')),
                ('destreza', models.SmallIntegerField(verbose_name='Destreza')),
                ('precisao', models.SmallIntegerField(verbose_name='Precisão')),
                ('inteligencia', models.SmallIntegerField(verbose_name='Inteligência')),
                ('sabedoria', models.SmallIntegerField(verbose_name='Sabedoria')),
                ('carisma', models.SmallIntegerField(verbose_name='Carisma')),
                ('resistencia', models.SmallIntegerField(verbose_name='Resistência')),
                ('foco', models.SmallIntegerField(verbose_name='Foco')),
                ('esquiva', models.SmallIntegerField(verbose_name='Esquiva')),
                ('sorte', models.SmallIntegerField(verbose_name='Sorte')),
            ],
        ),
        migrations.CreateModel(
            name='Descricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altura', models.PositiveSmallIntegerField(verbose_name='Altura')),
                ('cor_olho', models.CharField(max_length=100, verbose_name='Cor do olho')),
                ('cor_cabelo', models.CharField(max_length=100, verbose_name='Cor do cabelo')),
                ('cor_pele', models.CharField(max_length=100, verbose_name='Cor do pele')),
                ('peso', models.PositiveSmallIntegerField(verbose_name='Peso')),
                ('outras_caracteristicas', models.TextField(verbose_name='Outras Características')),
            ],
        ),
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('idade', models.PositiveSmallIntegerField(verbose_name='Idade')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('I', 'Indefinido')], max_length=1, verbose_name='Sexo')),
                ('profissao', models.CharField(max_length=50, verbose_name='Profissão')),
                ('tendencia', models.CharField(choices=[('LB', 'Leal e Bom'), ('NB', 'Neutro e Bom'), ('CB', 'Caótico e Bom'), ('LN', 'Leal e Neutro'), ('N', 'Neutro'), ('CN', 'Caótico e Neutro'), ('LM', 'Leal e Mau'), ('NM', 'Neutro e Mau'), ('CM', 'Caótico e Mau')], max_length=2, verbose_name='Tendência')),
                ('background', models.TextField(verbose_name='Background')),
                ('caracteristica_marcante', models.TextField(verbose_name='Característica Marcante')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='personagem/', verbose_name='Imagem')),
                ('atributo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='personagem.atributo')),
                ('cenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cenario', verbose_name='Cenário')),
                ('descricao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='personagem.descricao')),
            ],
            options={
                'verbose_name': 'Personagem',
                'verbose_name_plural': 'Personagens',
                'ordering': ['nome'],
            },
        ),
    ]
