# Generated by Django 3.2.6 on 2021-08-31 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagem',
            name='profissao',
            field=models.CharField(max_length=50, verbose_name='Profissão'),
        ),
    ]
