# Generated by Django 3.2.6 on 2021-09-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagem', '0002_alter_personagem_profissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='imagem_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='personagem/', verbose_name='Imagem de Perfil'),
        ),
    ]
